<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function helloworld_theme($existing, $type, $theme, $path) {
  $variables = array(
    'helloworld' => array(
      'variables' => array(
        'source_text' => NULL,
      ),
      'template' => 'helloworld',
    ),
  );
  return $variables;
}

function template_preprocess_helloworld(&$variables) {
  // Defines a list of acceptable punctuation.
  $punctuation = array('. ', '! ', '? ', '... ', ': ', '; ');

  // Loops over text, one paragraph at a time, taking it apart
  // and gluing it back together with random punctuation.
  for ($i = 0; $i < count($variables['source_text']); $i++) {
    $big_text = explode('. ', $variables['source_text'][$i]);
    for ($j = 0; $j < count($big_text)-1; $j++) {
      $big_text[$j] .= $punctuation[floor(mt_rand(0, count($punctuation)-1))];
    }
    $variables['source_text'][$i] = implode('', $big_text);
  }
}

/**
 * Implements hook_help().
 */
function helloworld_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.helloworld':
      $output = '';
      $output .= '<h2>' . t('Hello world button for drupal') . '</h2>';
      return $output;
  }
}
