helloworld.settings:
  type: config_object
  label: 'Hello world settings'
  mapping:
    helloworld:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Lorem ipsum generator page title:'
        source_text:
          type: text
          label: 'Source text for lorem ipsum generation:'
block.settings.helloworld_block:
  type: block_settings
  label: 'Hello world block'
  mapping:
    helloworld_block_settings:
      type: text
      label: 'Hello world block settings'
